rules = [
  OrganizeImports,
  TypelevelUnusedIO,
  TypelevelFs2SyncCompiler,
  TypelevelMapSequence,
  TypelevelAs,
  TypelevelUnusedShowInterpolator,
  TypelevelIORandomUUID,
]

OrganizeImports {
  targetDialect = Scala3
  # Blank line between each group
  groupedImports = Keep
  blankLines = Auto

  # Sort within each group
  importsOrder = Ascii
  importSelectorsOrder = Ascii

  groups = [
    "io.github.mercurievv."
    "re:javax?\\."
    "scala."
    "cats."
    "cats.effect."
    "io.circe."
    "fs2."
    "*"
  ]

  # Keep wildcard imports as-is
  removeUnused = true
}