addSbtPlugin("com.github.sbt" % "sbt-pgp" % "2.2.1")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.5.6")
addSbtPlugin("org.scalameta" % "sbt-mdoc" % "2.6.4")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.14.5")
addSbtPlugin("org.wartremover" %% "sbt-wartremover" % "3.5.6")
addSbtPlugin("org.jetbrains.scala" % "sbt-ide-settings" % "1.1.2")

addSbtPlugin("org.typelevel" % "sbt-typelevel" % "0.8.5")
addSbtPlugin("org.typelevel" % "sbt-typelevel-github" % "0.8.5")
addSbtPlugin("org.typelevel" % "sbt-typelevel-site" % "0.8.5")
